language: objective-c
osx_image: xcode7.2
xcode_project: EnhancedAutoReleasePool.xcodeproj
xcode_scheme: EnhancedAutoReleasePool
xcode_sdk: iphonesimulator9.2
env:
  global:
  - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.2"
  - FRAMEWORK_NAME=EnhancedAutoReleasePool
branches:
  only:
  - master
  - develop
  - "/^v?[0-9\\.]+/"
before_install:
- brew update
- brew unlink carthage
- brew install carthage
script:
- pod lib lint
- set -o pipefail
- xcodebuild -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk
  iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME"
  -destination "$DESTINATION" | xcpretty -c
before_deploy:
- carthage build --no-skip-current
- carthage archive "$FRAMEWORK_NAME"
deploy:
  provider: releases
  api_key:
    secure: wEfHicjQY9cOqjzcx1U6CBDeBBTQnV4kgSPSB85dKJqMQfHQ1b7NsEE0pfGIYd7PzUxowGwJnyPtjz4akHEwLmzWLikYcyAa/F49ozsJRfTrN5We7jTZA6TLgOmXT7SRsrwYF03vUcI74/SIBn3O27bh3wNjUIesjUsG59pwHK06XDrlP+SRigZVxzsq8T4EB+Pci7O3omy/lO81NBBzu8H2cPydDPpGyZOUbuLB767yi8AGnyYXf9QShsbw10mQdaZTY9/9PPiabGrWbmHkEUWlSyq63CpTVbhtJIXG9j6v2ZYZjgggYBD+P6fbMzh6iqz9NxdRT0Y5wRoEdh72zaLFGt0nQ6kY4GpoOfCZa8bEDRI3jhba1pURfpxByRjBpgoNe7de5jgQ1fBUkQbRks02qTj9GDKvH/BzwDpThr+Bj/espLCMdo+xgRFrXe7yE2sPDZOrQSJC33gSpDaTJ5U0A2NvvAtxxIR+8ZLIcXMus+Xfcye4BRWX2cYJbAi0XVePIF/lc7a9YCfXZPYCQbEsMKDLWRraqGbVo42GmDkzXS9lvuCEdSYzGrvx70QKpG/YHPlaA0Fwcn+WXRQUdBNYVxgphQDj0DbIpJ/kBOBw3mq/0nLYc8cKzPzJW3xojo0OEWMcRBgTMyC3cusf+orGxvdL/xYyBfoBfcDU744=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: "$TRAVIS_REPO_SLUG"
    tags: true
notifications:
  email: false
  slack:
    secure: g4xZWffoVbcScW7534/dlwm8OZ1diECOeJfWFRcLGzWDd6H0RtSKuk8ebFOLciNYDOjlf8H9+gktR1jis+jN1vv75SSKIhPqFJ2/B8srdha3EFEyFxzuIbCa2+1vbw/Y6z+Jb7+GGSzId+JVnoCsDlhxY8RLY23E5IJ1O2YCO4XSeothc1U5GNXlNhI6vKD6BSGD2oy15K6C1bAY0YkqSGVyGBBRbbczEjpeljHfw7BiGPfrTVJ65tCHzw9ZtIkevdA+LYSpcJ0EkF6i15xMViOzlxqr+s/6ABcf+9BYfpTlXQqLtqXOw1Ig+Cx4j7ORs/g6MFuEOSlNyXbsJ7gTDmiUuu+HnCcz2Moye45g8SOM5gOlDUOy8j+IALgFWdeeoIZLaAXr+U+trbvPLwRiOzryXYIAzIX5rjWz4Hm5eK1KmaCZX60hJm0z2RQ4q8PRJJLFkOY11xAldlS5tuVZBzPkBA6QJsW6UgON+5YjHjqPx0PSOTrvwY8PHvqrHbC4JvlKq1X42Ca/IN/Ac79G7GrWyAv9RKT68yQQKNa8p0ivb83EgmPAMXKzYRNUmbXyy+Ee/xUVUTs/Mm6tC+VkgFa4Df12JGh/9c7HAYac4zBqoJYABcQLmp43CbxHD1G9j2UnU60IWB5/aefMUeKS2HMbvZXazWp6wMQ0YKWawxc=
